"""Independent reducer: uses receipts and raw bytes, never the learner or runner reducer."""
import hashlib
import json
import math
from pathlib import Path

ALPHABET = b'0123'
DT = 30. / 14.


def checked_rows(raw_hex, rows, initial_history, initial_time):
    raw, history, t = bytes.fromhex(raw_hex), bytes.fromhex(initial_history), float(initial_time)
    if len(rows) != len(raw) or not raw:
        raise AssertionError('record count mismatch')
    total_loss, correct = 0., 0
    for byte, row in zip(raw, rows):
        t += DT
        if row['byte'] != byte or row['context'] != history.hex() or abs(row['t'] - t) > 1e-7:
            raise AssertionError('byte, pre-arrival context or clock mismatch')
        p = row['probabilities']
        if len(p) != 4 or any(not math.isfinite(v) or v <= 0 for v in p) or abs(sum(p) - 1) > 1e-12:
            raise AssertionError('invalid probability vector')
        emitted = ALPHABET[max(range(4), key=lambda i: p[i])]
        if emitted != row['emitted']:
            raise AssertionError('output not generated by model probability vector')
        error = [p[i] - int(b == byte) for i, b in enumerate(ALPHABET)]
        if any(abs(a - b) > 1e-12 for a, b in zip(error, row['signs'])) or len(row['signs']) != 4:
            raise AssertionError('update not derived from actual arriving byte and prior prediction')
        dose = row['native_write_l1']
        if len(dose) != 4 or any(not math.isfinite(x) or x < 0 for x in dose):
            raise AssertionError('invalid native write dose')
        if not row['plastic'] and any(dose):
            raise AssertionError('disabled branch wrote native memory')
        loss = -math.log2(p[ALPHABET.index(byte)])
        if abs(loss - row['loss_bits']) > 1e-12:
            raise AssertionError('predictive loss mismatch')
        correct += byte == emitted
        total_loss += loss
        history = (history + bytes([byte]))[-4:]
    return history, t, total_loss / len(raw), correct / len(raw)


def audit_receipt(receipt):
    if receipt['evidence'] != 'DEV_ONLY_E0_E1' or receipt['world'] not in (
            810001, 810101, 810201, 810202, 810203, 810204):
        raise AssertionError('undeclared DEV world or evidence level')
    history = {b: b'' for b in ('W', 'N_OLD', 'N_ALL')}
    t = {b: 0. for b in history}
    checked = 0
    for stage in ('old', 'day1', 'new', 'day2', 'revised'):
        if stage not in receipt['probes']:
            continue
        if stage in ('day1', 'day2'):
            t = {b: v + 86400. for b, v in t.items()}
        else:
            group = receipt['training'][stage]
            raw = bytes.fromhex(group['raw_hex'])
            if hashlib.sha256(raw).hexdigest() != group['sha256']:
                raise AssertionError('input hash mismatch')
            mapping = {bytes.fromhex(k): v for k, v in receipt['inputs'][stage].items()}
            for b, rows in group['branches'].items():
                expected = b == 'W' or (b == 'N_OLD' and stage != 'old')
                if any(row['plastic'] != expected for row in rows):
                    raise AssertionError('causal branch intervention mismatch')
                history[b], t[b], _, _ = checked_rows(group['raw_hex'], rows, history[b].hex(), t[b])
                for row in rows:
                    if bytes.fromhex(row['context']) in mapping and row['byte'] != mapping[bytes.fromhex(row['context'])]:
                        raise AssertionError('contradictory focal successor')
                checked += len(rows)
        for branch, sets in receipt['probes'][stage].items():
            source = 'W' if branch == 'NATIVE_ERASE' else branch
            for label, probe in sets.items():
                if probe['initial_history'] != history[source].hex() or abs(probe['initial_time'] - t[source]) > 1e-7:
                    raise AssertionError('probe initial context/time mismatch')
                if any(row['plastic'] for row in probe['rows']):
                    raise AssertionError('test probe learned')
                raw = bytes.fromhex(probe['raw_hex'])
                if hashlib.sha256(raw).hexdigest() != probe['sha256']:
                    raise AssertionError('probe input hash mismatch')
                _, _, bpb, acc = checked_rows(probe['raw_hex'], probe['rows'], probe['initial_history'], probe['initial_time'])
                focal = receipt['inputs']['old'] if label == 'old' else receipt['inputs'][label] if label != 'unchanged' else {
                    k: v for k, v in receipt['inputs']['old'].items() if k not in receipt['inputs']['revised']}
                focal_rows = [r for r in probe['rows'] if r['context'] in focal]
                correct = sum(r['byte'] == r['emitted'] for r in focal_rows) / len(focal_rows)
                focal_loss = sum(r['loss_bits'] for r in focal_rows) / len(focal_rows)
                metrics = probe['metrics']
                for name, value in [('all_byte_bpb', bpb), ('all_byte_accuracy', acc), ('focal_accuracy', correct), ('focal_bpb', focal_loss)]:
                    if abs(metrics[name] - value) > 1e-12:
                        raise AssertionError('published metric mismatch')
                if metrics['all_byte_count'] != len(raw) or metrics['focal_count'] != len(focal_rows):
                    raise AssertionError('metric denominator mismatch')
                if branch == 'NATIVE_ERASE' and any(abs(p - .25) > 1e-12 for r in probe['rows'] for p in r['probabilities']):
                    raise AssertionError('native erase retained learned output')
                checked += len(probe['rows'])
        if max(t.values()) != min(t.values()):
            raise AssertionError('branches have different clocks')
    return dict(verdict='PASS', independently_checked_rows=checked)


if __name__ == '__main__':
    import sys
    for filename in sys.argv[1:]:
        print(json.dumps(dict(file=filename, **audit_receipt(json.loads(Path(filename).read_text())))))
